In [1]:
import os
import sys
import warnings
import pandas as pd
import re
from os import path

from pandas.core.common import SettingWithCopyWarning
warnings.simplefilter(action="ignore", category=SettingWithCopyWarning)

from IPython.core.display import display, HTML
display(HTML("<style>.container { width:80% !important; }</style>"))

pd.set_option("display.max_rows", 2000)

sys.path.append("/src") # add spending tracker dir to path

from common.constants import *

from transaction_data_tools.plugins import chase_plugin
from transaction_data_tools.plugins import amazon_plugin
from transaction_data_tools.plugins import fidelity_rewards_plugin
from transaction_data_tools.plugins import fidelity_cash_plugin
from transaction_data_tools.plugins import mint_plugin

from transaction_data_tools.data_update import get_downloads
from transaction_data_tools.data_setup_utils import update_raw_transactions_file
from transaction_data_tools.data_loader import load_raw_trans

from app.utils import to_snake

In [2]:
downloads = get_downloads()

# Amazon

In [3]:
logs = amazon_plugin.update(downloads)
print(logs)

UPDATING AMAZON RECORDS

updating: /src/transaction_data/raw/amazon/transactions.csv

using: /src/transaction_data/downloads/01-Jan-2020_to_26-Jul-2021.csv

New transactions: 0. Total: 222

--------------------

In [4]:
amazon_df = amazon_plugin.load_trans()
amazon_df.head()

,date,transaction_type,amount,account_name,original_description
0,2020-02-24,debit,10.59,AMAZON,SYLVANIA 7506ST.BP2 7506 SilverStar High Perfo...
1,2020-02-24,debit,26.45,AMAZON,Jazz Saxophone Etudes For Alto & Tenor: Book &...
2,2020-02-24,debit,44.39,AMAZON,"Filtrete 16x25x1, AC Furnace Air Filter, MPR 1..."
3,2020-02-27,debit,20.03,AMAZON,ColorGround Long Straight Brown 80S Mullet Dis...
4,2020-03-05,debit,32.81,AMAZON,Vandoren SR2625R Alto Sax JAVA Red Reeds Stren...

# Chase

In [3]:
mint_plugin.get_filename(downloads)

'transactions.csv'

In [4]:
logs = mint_plugin.update(downloads)
print(logs)

UPDATING MINT TRANSACTIONS

updating: /src/transaction_data/raw/mint/transactions.csv

using: /src/transaction_data/downloads/transactions.csv

New transactions: 0. Total: 1827

--------------------

In [8]:
df = mint_plugin.load_trans()
df.head(30)

,date,transaction_type,amount,account_name,original_description
0,1/02/2020,credit,450.00,CHASE COLLEGE,REMOTE ONLINE DEPOSIT #
1,1/02/2020,debit,6.88,CHASE COLLEGE,7-ELEVEN ARLINGTON VA
2,1/02/2020,debit,1190.00,CHASE COLLEGE,QuickPay with Zelle payment to I
3,1/02/2020,debit,71.29,CHASE COLLEGE,USAA P&C EXT AUTOPAY 1896
4,1/03/2020,debit,29.99,CHASE COLLEGE,APPLE.COM/BILL 866-712-7753 CA
5,1/03/2020,debit,56.73,CHASE COLLEGE,HARRIS TEETER 0279 FALLS CHURCH
6,1/04/2021,debit,3.00,CHASE COLLEGE,ARLINGTON METER PARKING ARLINGTO
7,1/04/2021,debit,25.96,CHASE COLLEGE,PHILZ COFFEE WWW.PHILZCOFF CA
8,1/04/2021,debit,86.08,CHASE COLLEGE,SQ *BEARDED GOAT BARBER Arlingto
9,1/04/2021,debit,53.04,CHASE COLLEGE,UBER EATS HELP.UBER.COM CA
10,1/04/2021,debit,57.46,CHASE COLLEGE,USAA P&C EXT AUTOPAY 1896
11,1/05/2021,debit,60.56,CHASE COLLEGE,SPIDER KELLYS ARLINGTON VA
12,1/05/2021,debit,1581.35,CHASE COLLEGE,Turkson Manageme Payment 3551
13,1/05/2021,debit,26.40,CHASE COLLEGE,UBER EATS HELP.UBER.COM CA
14,1/06/2020,debit,50.00,CHASE COLLEGE,CAMP SUNSHINE ME WWW.CAMPSUNSH M
15,1/06/2020,debit,2.59,CHASE COLLEGE,LIM*RIDE COST 8885463345 CA
16,1/06/2020,debit,39.99,CHASE COLLEGE,MSF* GOLD'S GYM VA-BAL 703-51646
17,1/06/2020,debit,5.05,CHASE COLLEGE,PARKMOBILE 770-818-9036 DC
18,1/06/2020,debit,11.55,CHASE COLLEGE,SWEETGREEN BTN 202-813-9439 VA
19,1/06/2020,debit,31.10,CHASE COLLEGE,TRADER JOE'S # 644 BAILEYS XRDS
20,1/06/2021,debit,40.94,CHASE COLLEGE,HARRIS TE 900 ARMY NAV ARLINGTON
21,1/07/2021,debit,405.67,CHASE COLLEGE,Payment to Chase card ending in
22,1/08/2020,debit,3.18,CHASE COLLEGE,7-ELEVEN WOODBRIDGE VA
23,1/08/2020,debit,2.50,CHASE COLLEGE,ARLINGTON METER PARKING ARLINGTO
24,1/08/2020,debit,195.00,CHASE COLLEGE,MIND BODY HEALTH LLC STRIPE.COM
25,1/08/2020,debit,40.20,CHASE COLLEGE,RICE PAPER TASTE OF V FALLS CHUR
26,1/08/2020,debit,13.42,CHASE COLLEGE,TST* NORTHSIDE SOCIAL C ARLINGTO
27,1/08/2021,debit,15.99,CHASE COLLEGE,APPLE.COM/BILL 866-712-7753 CA
28,1/08/2021,debit,600.00,CHASE COLLEGE,ROBINHOOD Funds 1455
29,1/08/2021,debit,29.97,CHASE COLLEGE,UBER EATS HELP.UBER.COM CA